# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(576, 532)
        self.login_label = QtWidgets.QLabel(Dialog)
        self.login_label.setGeometry(QtCore.QRect(190, 160, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.login_label.setFont(font)
        self.login_label.setAlignment(QtCore.Qt.AlignCenter)
        self.login_label.setObjectName("login_label")
        self.id_text = QtWidgets.QLineEdit(Dialog)
        self.id_text.setGeometry(QtCore.QRect(200, 240, 201, 21))
        self.id_text.setObjectName("id_text")
        self.pw_text = QtWidgets.QLineEdit(Dialog)
        self.pw_text.setGeometry(QtCore.QRect(200, 290, 201, 21))
        self.pw_text.setObjectName("pw_text")
        self.id_label = QtWidgets.QLabel(Dialog)
        self.id_label.setGeometry(QtCore.QRect(170, 240, 16, 16))
        self.id_label.setObjectName("id_label")
        self.pw_label = QtWidgets.QLabel(Dialog)
        self.pw_label.setGeometry(QtCore.QRect(170, 290, 21, 16))
        self.pw_label.setObjectName("pw_label")
        self.login_button = QtWidgets.QPushButton(Dialog)
        self.login_button.setGeometry(QtCore.QRect(250, 340, 93, 28))
        self.login_button.setObjectName("login_button")
        self.error_text = QtWidgets.QLabel(Dialog)
        self.error_text.setGeometry(QtCore.QRect(150, 400, 291, 20))
        self.error_text.setText("")
        self.error_text.setObjectName("error_text")
        self.logo_image = QtWidgets.QLabel(Dialog)
        self.logo_image.setGeometry(QtCore.QRect(250, 40, 101, 91))
        self.logo_image.setText("")
        self.logo_image.setObjectName("logo_image")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.login_label.setText(_translate("Dialog", "DYMF"))
        self.id_label.setText(_translate("Dialog", "id"))
        self.pw_label.setText(_translate("Dialog", "pw"))
        self.login_button.setText(_translate("Dialog", "로그인"))
